name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test
        run: mvn -B verify

      - name: Upload successful test reports
        if: success()  # Only when tests pass
        uses: actions/upload-artifact@v4
        with:
          name: passed-tests
          path: target/surefire-reports
          retention-days: 7

      - name: Upload failed test reports
        if: failure()  # Only when tests fail
        uses: actions/upload-artifact@v4
        with:
          name: failed-tests
          path: |
            target/surefire-reports
            target/failsafe-reports
          retention-days: 7